### ISSUE TITLE
Port to Telegram Web

### ISSUE THREAD

**Issue by Barina** [vednoc/dark-whatsapp#99]
Can you please port this to Telegram Web as well?
Would be awesome

**Comment by E-RELevant** [comment]
This is a custom design for the web version of **WhatsApp**. There is no connection between the two things, and this is a completely different project. Feel free to look for a suitable style through the Stylus extension or any other way you choose.

**Comment by vednoc** [comment]
This is out of scope of this project.

I already have quite a few other userstyles that I maintain for sites that I actually use, so this wouldn't make a lot of sense for me to do.

If someone is willing to port this over to Telegram Web, go for it! :smiley:

**Comment by Barina** [comment]
I started to work on a port for Telegram web :)
Can you please check the credits for me?
Also would be nice to have some suggestions as I'm not a FE\WEB developer

**Comment by vednoc** [comment]
You did a phenomenal job porting it to Telegram so far!

I'll link to your project in the readme, and probably contribute some code as well. If you have a group, give me a link and I'll join. :smiley: 

As for suggestions, I highly suggest you steal [mixins and variables][0] to make it easier on your hands, and nest selectors where possible so that you don't repeat the code. Also [stylus-lang documentation][1] is quite helpful.


[0]: https://github.com/vednoc/dark-whatsapp/blob/d35c2e9977cfdd8ef9c968be5a6b98823460b720/wa.user.styl#L195-L239
[1]: https://stylus-lang.com/

**Comment by Barina** [comment]
Thanks :D 
Yea I saw mixins and function can be quite useful I'm gonna use that 
and variables causes me problems at first but now they ok.. what IDE you use to write the style? the stylus editor is kinda meh...

**Comment by vednoc** [comment]
Out of the bunch I've used, VSCode/VSCodium had quite a few extensions for stylus-lang, but I ended up only using the one that provides syntax highlighting. These days I'm using (Doom) Emacs, and while it's definitely not the best environment for stylus-lang, I really enjoy using it.

**Comment by Barina** [comment]
None of them providing a "live preview" like the stylus editor does I find myself copy&pasting from\to VSCode which isn't ideal 
Do you know any way of setting a style from a local file instead of using stylus addon? so it'll update on save or something..

**Comment by vednoc** [comment]
Clone your repository and open the `Dark-Telegram.styl` in your browser. If you're using Chromium-based browser, you'll have to enable "Allow access to file URLs" for Stylus on the extension details page. More info [here][0].

If I'm not mistaken, there is still a bug that broke that functionality in Chromium 80+ and Stylus 1.5.9, but it's fixed in Stylus 1.5.10 and it also works fine in Firefox. I have it [sideloaded][1] in Brave when something is specific to Chromium.


[0]: https://github.com/openstyles/stylus/wiki/UserCSS-authors#initial-installation
[1]: https://github.com/openstyles/stylus/wiki/Install-Stylus-from-GitHub

**Comment by Barina** [comment]
Lol so FF it is.. at least up to next release :P

Oh and we can open a group in Telegram it'll be nice :)

**Comment by vednoc** [comment]
For some reason I couldn't install Stylus in Brave so I had to do it. :grimacing: The process is surprisingly simple, just clone the Stylus repository and "load unpacked" from extensions page — that's it!

I'm pretty sure you'll figure out how to add me there. :smirk: :smile:

**Comment by Barina** [comment]
I just installed stylus on brave (never used brave before thought I'll give it a try :) )
But that bug still prevent me using the user.css file like Chrome and Edge 
But it works on FF which I already have so it's good

BTW styl files doesn't work at all for me they just open in the browser like a text file
The user.css forks ok

Oh and I created a new group in Telegram (found 2 bugs in the process 😅)
https://t.me/joinchat/CZNZlBroTZjlzRaF_wqR1Q
